# Generated by Django 5.1.6 on 2026-06-30 14:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero_serie', models.CharField(max_length=64, unique=True)),
                ('modele', models.CharField(max_length=100)),
                ('type_station', models.CharField(choices=[('STATION_TRAM', 'Station Tram'), ('STATION_BUS', 'Station Bus'), ('STATION_METRO', 'Station Métro'), ('HUB_INTERMODAL', 'Hub Intermodal')], max_length=30)),
                ('statut', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('EN_PANNE', 'En panne'), ('EN_MAINTENANCE', 'En maintenance'), ('HORS_SERVICE', 'Hors service')], default='DISPONIBLE', max_length=20)),
                ('batterie', models.PositiveSmallIntegerField(default=100)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
            ],
            options={
                'db_table': 'machine',
                'ordering': ['numero_serie'],
            },
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=200)),
                ('type_station', models.CharField(choices=[('STATION_TRAM', 'Station Tram'), ('STATION_BUS', 'Station Bus'), ('STATION_METRO', 'Station Métro'), ('HUB_INTERMODAL', 'Hub Intermodal')], max_length=30)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('lignes_desservies', models.JSONField(blank=True, default=list)),
                ('statut', models.CharField(choices=[('OUVERTE', 'Ouverte'), ('FERMEE', 'Fermée'), ('MAINTENANCE', 'Maintenance'), ('SATUREE', 'Saturée')], default='OUVERTE', max_length=20)),
            ],
            options={
                'db_table': 'station',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=100)),
                ('resource', models.CharField(blank=True, default='', max_length=200)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'audit_log',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Moto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type_moto', models.CharField(choices=[('ELECTRIQUE', 'Électrique'), ('THERMIQUE', 'Thermique')], max_length=20)),
                ('autonomie', models.PositiveIntegerField(help_text='Autonomie en km')),
                ('niveau_batterie', models.PositiveSmallIntegerField(default=100)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('position_timestamp', models.DateTimeField()),
                ('statut_moto', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('EN_MISSION', 'En mission'), ('EN_MAINTENANCE', 'En maintenance'), ('HORS_SERVICE', 'Hors service')], default='DISPONIBLE', max_length=20)),
                ('kilometrage', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('agent_assigne', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='motos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'moto',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='MotoPositionHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('kilometrage', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('moto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='operational.moto')),
            ],
            options={
                'db_table': 'moto_position_history',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Rapport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type_rapport', models.CharField(choices=[('QUOTIDIEN', 'Quotidien'), ('HEBDOMADAIRE', 'Hebdomadaire'), ('MENSUEL', 'Mensuel'), ('PERFORMANCE', 'Performance'), ('STOCK', 'Stock'), ('TRANSACTION', 'Transaction'), ('DEFECTUEUX', 'Défectueux'), ('STATION', 'Station')], max_length=20)),
                ('periode_debut', models.DateField()),
                ('periode_fin', models.DateField()),
                ('donnees', models.JSONField(blank=True, default=dict)),
                ('statut_generation', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('EN_COURS', 'En cours'), ('TERMINE', 'Terminé'), ('ECHEC', 'Échec')], default='EN_ATTENTE', max_length=20)),
                ('fichier_url', models.CharField(blank=True, default='', max_length=500)),
                ('date_generation', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'rapport',
                'ordering': ['-date_generation'],
            },
        ),
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_debut', models.DateTimeField()),
                ('date_fin', models.DateTimeField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('PLANIFIEE', 'Planifiée'), ('EN_COURS', 'En cours'), ('TERMINEE', 'Terminée'), ('ANNULEE', 'Annulée')], default='PLANIFIEE', max_length=20)),
                ('zone_couverture', models.CharField(max_length=100)),
                ('donnees_telechargees', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, default='')),
                ('duree_prevue_minutes', models.PositiveIntegerField(default=480)),
                ('cause_annulation', models.CharField(blank=True, default='', max_length=255)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='missions', to=settings.AUTH_USER_MODEL)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='missions', to='operational.machine')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='missions', to='operational.station')),
            ],
            options={
                'db_table': 'mission',
                'ordering': ['-date_debut'],
            },
        ),
        migrations.AddField(
            model_name='machine',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='machines', to='operational.station'),
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('type_paiement', models.CharField(choices=[('CB', 'Carte bancaire'), ('TRANSPORT', 'Transport'), ('ESPECES', 'Espèces'), ('MOBILE', 'Mobile')], max_length=20)),
                ('statut_validation', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('VALIDEE', 'Validée'), ('REJETEE', 'Rejetée')], default='EN_ATTENTE', max_length=20)),
                ('statut_sync', models.CharField(choices=[('SYNC', 'Synchronisé'), ('EN_ATTENTE', 'En attente'), ('ECHEC', 'Échec')], default='EN_ATTENTE', max_length=20)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('numero_transaction', models.CharField(max_length=64, unique=True)),
                ('type_carte', models.CharField(blank=True, default='', max_length=50)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to=settings.AUTH_USER_MODEL)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='operational.machine')),
                ('mission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='operational.mission')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='operational.station')),
            ],
            options={
                'db_table': 'transaction',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='StockCarte',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type_carte', models.CharField(choices=[('NAVIGO', 'Navigo'), ('TICKET_T_PLUS', 'Ticket t+'), ('CARTE_JEUNE', 'Carte Jeune'), ('CARTE_SENIOR', 'Carte Senior'), ('PASS_JOUR', 'Pass Jour')], max_length=30)),
                ('quantite_actuelle', models.PositiveIntegerField()),
                ('quantite_initiale', models.PositiveIntegerField()),
                ('seuil_alerte', models.PositiveIntegerField(default=50)),
                ('taux_defectueux', models.DecimalField(decimal_places=4, default=0, max_digits=5)),
                ('date_mise_a_jour', models.DateTimeField(auto_now=True)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stocks', to='operational.station')),
            ],
            options={
                'db_table': 'stock_carte',
                'ordering': ['station', 'type_carte'],
                'unique_together': {('type_carte', 'station')},
            },
        ),
    ]
